create table appointments (doctor_id integer, id integer not null auto_increment, user_id integer, appointment_date_time datetime(6), note varchar(255), status enum ('AWAITING_DEPOSIT','CANCELLED','CANCELLED_NO_REFUND','CANCELLED_REFUND','COMPLETED','CONFIRMED','DEPOSIT_PAID','PENDING'), primary key (id)) engine=InnoDB;
create table chat_messages (id integer not null auto_increment, is_read bit not null, receiver_user_id integer not null, sender_user_id integer not null, created_at datetime(6) not null, sent_at datetime(6) not null, updated_at datetime(6) not null, content TEXT not null, sender_type enum ('DOCTOR','PATIENT','SYSTEM') not null, primary key (id)) engine=InnoDB;
create table departments (id integer not null auto_increment, is_active BIT DEFAULT 1, created_at datetime(6) not null, updated_at datetime(6) not null, description varchar(255), name varchar(255), primary key (id)) engine=InnoDB;
create table doctors (departments_id integer, experience_years integer not null, id integer not null auto_increment, is_active BIT DEFAULT 1, is_featured BIT DEFAULT 0, user_id integer not null, description varchar(255), image_url varchar(255), primary key (id)) engine=InnoDB;
create table notifications (id integer not null auto_increment, is_read BIT DEFAULT 0, user_id integer, created_at datetime(6), message varchar(255), primary key (id)) engine=InnoDB;
create table payments (amount float(53) not null, appointment_id integer, id integer not null auto_increment, is_deposit BIT DEFAULT 0, payment_method tinyint check (payment_method between 0 and 2), status tinyint check (status between 0 and 3), payment_date datetime(6), payment_code varchar(50), transaction_id varchar(50), gateway_transaction_no varchar(100), response_code varchar(100), secure_hash varchar(500), payment_url varchar(1000), primary key (id), check (payment_method BETWEEN 0 AND 2 AND status BETWEEN 0 AND 3)) engine=InnoDB;
create table review (doctors_id integer, id integer not null auto_increment, is_active BIT DEFAULT 1, rating integer not null, user_id integer, create_at datetime(6), comment varchar(255), primary key (id)) engine=InnoDB;
create table role (is_active BIT DEFAULT 1, roleid integer not null auto_increment, description varchar(255), role_name varchar(255), primary key (roleid)) engine=InnoDB;
create table schedules (day_of_week tinyint check (day_of_week between 0 and 6), doctor_id integer, id integer not null auto_increment, is_active BIT DEFAULT 1, end_at datetime(6), start_at datetime(6), primary key (id)) engine=InnoDB;
create table site_info (id integer not null auto_increment, is_active BIT DEFAULT 1, created_at datetime(6) not null, updated_at datetime(6) not null, info_key varchar(255), value varchar(255), primary key (id)) engine=InnoDB;
create table user (created_at date, date_of_birth date, is_active BIT DEFAULT 1, role_id integer, user_id integer not null auto_increment, address varchar(255), avatar_url varchar(255), email varchar(255), full_name varchar(255), password varchar(255), phone varchar(255), user_name varchar(255), primary key (user_id)) engine=InnoDB;
alter table doctors add constraint UKt1f6cueqyjwx5ghew9ar1exe3 unique (user_id);
alter table payments add constraint UKn939tpje3kshdfk6pbi7ewwj7 unique (payment_code);
alter table payments add constraint UKlryndveuwa4k5qthti0pkmtlx unique (transaction_id);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FKs5hmxf6861r976vv3chddfyo4 foreign key (user_id) references user (user_id);
alter table doctors add constraint FKoxpotfblgvkw1371ej8xadbeq foreign key (departments_id) references departments (id);
alter table doctors add constraint FK1kdokdbkomgra23x78ttur43p foreign key (user_id) references user (user_id);
alter table notifications add constraint FK3dt2b80521eynbjg4nehtjnhy foreign key (user_id) references user (user_id);
alter table payments add constraint FK9a0odew03qao7nlbdsesrux5u foreign key (appointment_id) references appointments (id);
alter table review add constraint FK3ksragtigskoyhjl8udhvmqtx foreign key (doctors_id) references doctors (id);
alter table review add constraint FKiyf57dy48lyiftdrf7y87rnxi foreign key (user_id) references user (user_id);
alter table schedules add constraint FKfpyatautb52nts46e1y1y4nvg foreign key (doctor_id) references doctors (id);
alter table user add constraint FKn82ha3ccdebhokx3a8fgdqeyy foreign key (role_id) references role (roleid);
